-- 코드를 입력하세요
SELECT DISTINCT m.CART_ID
FROM (SELECT CART_ID 
      FROM CART_PRODUCTS 
      WHERE NAME = "Milk") m
JOIN (SELECT CART_ID
      FROM CART_PRODUCTS 
      WHERE NAME = "Yogurt") y
ON m.CART_ID = y.CART_ID
ORDER BY m.CART_ID;