-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, (PRICE * SUM(SALES_AMOUNT)) AS SALES
FROM PRODUCT p
JOIN OFFLINE_SALE s 
ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE ASC;