-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, CEIL(DAILY_FEE * 30 * DISCOUNT_RATE) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN (SELECT CAR_TYPE, ((100 - DISCOUNT_RATE) / 100) AS DISCOUNT_RATE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
      WHERE DURATION_TYPE LIKE "30%") d
ON c.CAR_TYPE = d.CAR_TYPE
HAVING (CAR_TYPE = "세단" OR CAR_TYPE = "SUV")
AND CAR_ID NOT IN (SELECT CAR_ID 
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                   WHERE (START_DATE >= "2022-11-01" OR END_DATE >= "2022-11-01")
                   AND (START_DATE <= "2022-11-30" OR END_DATE <= "2022-11-30"))
AND FEE >= 500000
AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;