-- 코드를 입력하세요
WITH u AS (SELECT USER_ID
              FROM USER_INFO
              WHERE YEAR(JOINED) = 2021)
SELECT YEAR, MONTH, COUNT(USER_ID) AS PURCHASED_USERS, 
        ROUND(COUNT(USER_ID) / (SELECT COUNT(*) FROM u), 1) AS PUCHASED_RATIO
FROM (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
      FROM ONLINE_SALE 
      WHERE USER_ID IN (SELECT USER_ID FROM u)
      GROUP BY YEAR, MONTH, USER_ID
      HAVING SUM(SALES_AMOUNT) > 0) s
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;
