-- 코드를 입력하세요
WITH dc AS (SELECT CASE WHEN DURATION_TYPE LIKE "7%" THEN 7
                        WHEN DURATION_TYPE LIKE "30%" THEN 30
                        ELSE 90
                   END AS DURATION_TYPE,
                (100 - DISCOUNT_RATE) / 100 AS DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE = "트럭")
SELECT HISTORY_ID, 
        CASE WHEN DURATION >= 90 
                THEN CEIL(DAILY_FEE * DURATION * 
                    (SELECT DISCOUNT_RATE FROM dc WHERE DURATION_TYPE = 90))
             WHEN DURATION >= 30 
                THEN CEIL(DAILY_FEE * DURATION * 
                    (SELECT DISCOUNT_RATE FROM dc WHERE DURATION_TYPE = 30))
             WHEN DURATION >= 6 
                THEN CEIL(DAILY_FEE * DURATION * 
                    (SELECT DISCOUNT_RATE FROM dc WHERE DURATION_TYPE = 7))
             ELSE DAILY_FEE * DURATION
        END AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN (SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) h
ON c.CAR_ID = h.CAR_ID
WHERE c.CAR_TYPE = "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC;
