-- 코드를 입력하세요
SELECT a.APNT_NO, PT_NAME, p.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT p
JOIN APPOINTMENT a
ON p.PT_NO = a.PT_NO
JOIN DOCTOR d
ON a.MDDR_ID = d.DR_ID
WHERE DATEDIFF(APNT_YMD, "2022-04-13") = 0
AND APNT_CNCL_YN = "N"
AND a.MCDP_CD = "CS"
ORDER BY APNT_YMD;