-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT tree.ITEM_ID
    FROM ITEM_INFO info
    JOIN ITEM_TREE tree
    ON info.ITEM_ID = tree.PARENT_ITEM_ID
    AND info.RARITY = "RARE")
ORDER BY ITEM_ID DESC;