-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM SKILLCODES skl
JOIN DEVELOPERS dev
WHERE (skl.NAME = "Python" AND skl.CODE & dev.SKILL_CODE > 0)
OR (skl.NAME = "C#" AND skl.CODE & dev.SKILL_CODE > 0)
ORDER BY ID;