-- 코드를 작성해주세요
# SELECT ID, FISH_NAME, l.LENGTH
# FROM FISH_INFO i
# JOIN (SELECT FISH_TYPE, MAX(LENGTH) LENGTH
#       FROM FISH_INFO
#       GROUP BY FISH_TYPE) l
# ON l.FISH_TYPE = i.FISH_TYPE AND l.LENGTH = i.LENGTH
# JOIN FISH_NAME_INFO ni 
# ON i.FISH_TYPE = ni.FISH_TYPE
# ORDER BY ID;

SELECT i.ID, FISH_NAME, LENGTH
FROM FISH_INFO i
JOIN (SELECT ID, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE 
                                ORDER BY LENGTH DESC) AS ROW_NUM
      FROM FISH_INFO) rn
ON i.ID = rn.ID
JOIN FISH_NAME_INFO ni 
ON i.FISH_TYPE = ni.FISH_TYPE
WHERE rn.ROW_NUM = 1
ORDER BY ID;