-- 코드를 입력하세요
WITH max_p AS (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
             FROM FOOD_PRODUCT 
             GROUP BY CATEGORY)
SELECT m.CATEGORY, m.MAX_PRICE, f.PRODUCT_NAME
FROM max_p m
JOIN FOOD_PRODUCT f
ON m.CATEGORY = f.CATEGORY
WHERE m.CATEGORY IN ("과자", "국", "김치", "식용유")
AND PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC;
