-- 코드를 작성해주세요
WITH FIXED_LENGTH AS (SELECT FISH_TYPE, CASE WHEN LENGTH IS NULL THEN 10
                                             ELSE LENGTH
                                        END AS FIXED_LENGTH
                      FROM FISH_INFO)
SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, i.FISH_TYPE
FROM FISH_INFO i
JOIN (SELECT FISH_TYPE, AVG(FIXED_LENGTH) AS AVG_LENGTH
      FROM FIXED_LENGTH
      GROUP BY FISH_TYPE
      HAVING AVG_LENGTH >= 33) sub
ON i.FISH_TYPE = sub.FISH_TYPE
GROUP BY i.FISH_TYPE
ORDER BY i.FISH_TYPE;